name: "action example"
description: "build some artifacts."
inputs:
  task:
      required: true
      type: string
      description: "Mise task to run"
  artifact:
    description: "Artifact name to build"
    required: true
  apt_packages:
    description: "Space-separated list of apt packages to install"
    required: false
outputs:
  artifact:
    description: "Name of the artifact built"
    value: "${{ steps.build.outputs.artifact }}"
  status:
    description: "Status of the build"
    value: "${{ steps.build.outputs.status }}"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
    - name: Install apt packages
      if: ${{ inputs.apt_packages != '' }}
      shell: bash
      run: sudo apt-get install -y ${{ inputs.apt_packages }}
    - name: Build
      shell: bash
      run: mise "${{ inputs.task }}"
